/* Generated by Yosys 0.22+1 (git sha1 c4a52b1b0, gcc 14.0.0 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "./source/upcounter.v:6.1-19.10" *)
module upcounter(clk, rst_n, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "./source/upcounter.v:8.7-8.10" *)
  input clk;
  wire clk;
  (* src = "./source/upcounter.v:10.18-10.23" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "./source/upcounter.v:9.7-9.12" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _09_ (
    .A(rst_n),
    .SLEEP(count[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__o21ai_0 _10_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(rst_n),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _11_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand3_1 _12_ (
    .A(count[0]),
    .B(count[2]),
    .C(count[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _13_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3b_1 _14_ (
    .A_N(_06_),
    .B(rst_n),
    .C(_05_),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand4_1 _15_ (
    .A(count[0]),
    .B(count[2]),
    .C(count[3]),
    .D(count[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a31o_1 _16_ (
    .A1(count[0]),
    .A2(count[2]),
    .A3(count[1]),
    .B1(count[3]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and3_1 _17_ (
    .A(rst_n),
    .B(_07_),
    .C(_08_),
    .X(_03_)
  );
  (* src = "./source/upcounter.v:12.1-17.4" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  (* src = "./source/upcounter.v:12.1-17.4" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  (* src = "./source/upcounter.v:12.1-17.4" *)
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  (* src = "./source/upcounter.v:12.1-17.4" *)
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule
